DROP TABLE IF EXISTS WALLETTRANSACTION;

CREATE TABLE WALLETTRANSACTION (
    id bigint PRIMARY KEY,
    type smallint not null,
	description varchar(100),
	created_at varchar(20) not null,
	wallet_id UUID NOT NULL
);

ALTER TABLE WALLETTRANSACTION ADD CONSTRAINT FK_WALLETTRANSACTION_WALLET FOREIGN KEY (wallet_id) references wallet(id);
ALTER TABLE WALLETTRANSACTION ADD CONSTRAINT CHECK_TYPE CHECK(type IN (1,2));
