DROP TABLE IF EXISTS WALLETTRANSACTION CASCADE;

CREATE TABLE WALLETTRANSACTION (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type smallint NOT NULL,
    description varchar(100),
    wallet_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_WALLETTRANSACTION_WALLET FOREIGN KEY (wallet_id) REFERENCES wallet(id),
    CONSTRAINT CK_TYPE CHECK(type IN (1,2))
);
